# Generated by Django 5.0.4 on 2024-05-21 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_presenca_aluno'),
        ('secretaria', '0004_turma_alter_cadastro_aluno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.cadastro_aluno'),
        ),
    ]
