# Generated by Django 5.0.4 on 2024-11-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merenda',
            name='consumo',
            field=models.IntegerField(default=0),
        ),
    ]
