# Generated by Django 5.0.4 on 2024-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_professor',
            name='turma',
        ),
        migrations.AddField(
            model_name='cadastro_professor',
            name='turmas',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Turmas',
        ),
    ]
