# Generated by Django 5.0.4 on 2024-05-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_remove_cadastro_professor_turma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_mae', models.CharField(max_length=200)),
                ('nome_pai', models.CharField(max_length=200)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cadunico', models.IntegerField()),
                ('ra', models.IntegerField()),
                ('foto', models.ImageField(upload_to='perfil_aluno')),
                ('turma', models.CharField(max_length=20)),
                ('periodo', models.CharField(max_length=20)),
            ],
        ),
    ]
