# Generated by Django 5.0.4 on 2024-05-18 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_cadastro_aluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cadastro_aluno',
            options={'ordering': ('nome',)},
        ),
        migrations.RemoveField(
            model_name='cadastro_professor',
            name='turmas',
        ),
        migrations.AddField(
            model_name='cadastro_aluno',
            name='status_presenca',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadastro_aluno',
            name='cadunico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro_aluno',
            name='ra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro_professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadastro_professor',
            name='turma',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='secretaria.turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro_aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='secretaria.turma'),
        ),
    ]
