# Generated by Django 5.0.4 on 2024-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_turma_alter_cadastro_aluno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
                ('total_alunos_presentes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cadastro_professor',
            name='cidade',
            field=models.CharField(default=8, max_length=50),
            preserve_default=False,
        ),
    ]
