# Generated by Django 5.0.4 on 2024-11-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_cadastro_aluno_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_aluno',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_professor',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
