# Generated by Django 5.0.4 on 2024-11-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_alter_cadastro_aluno_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_professor',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.turma'),
        ),
    ]
