# Generated by Django 5.0.2 on 2025-03-09 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0009_alter_cadastro_aluno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_professor',
            name='foto',
            field=models.ImageField(blank=True, default='perfil_professor/default_professor.jpg', null=True, upload_to='perfil_professor'),
        ),
        migrations.AlterField(
            model_name='historicochamada',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.turma'),
        ),
    ]
